# Generated by Django 3.2 on 2021-04-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixkey', models.CharField(max_length=255, verbose_name='Chave do PIX')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Pagamento PIX')),
                ('merchant_name', models.CharField(max_length=255, verbose_name='Nome do Titular da Conta')),
                ('merchant_city', models.CharField(max_length=255, verbose_name='Nome da Cidade do Titular da Conta')),
                ('txid', models.CharField(max_length=255, verbose_name='ID da Transação')),
                ('amount', models.CharField(max_length=255, verbose_name='Valor da Transação')),
            ],
            options={
                'verbose_name': 'Pix',
                'verbose_name_plural': 'Pixs',
            },
        ),
    ]
